<?php
    $customerTypes = $block->getAllowedCustomerTypesData();
?>
<?php if (count($customerTypes) > 1): ?>
<div class="customer-type-switcher">
    <?php foreach ($customerTypes as $num => $customerType): ?>
        <?php if (isset($customerType['isActive'])): ?>
            <?= __($customerType['title']) ?>
        <?php else: ?>
            <a href ="<?= $customerType['checkoutUrl'] ?>">
                <?= __($customerType['title']) ?>
            </a>
        <?php endif; ?>
        <?= (1 == $num) ? '|' : '' ?>
    <?php endforeach; ?>
</div>
<?php endif; ?>